[versions]
agp = "8.7.1"
androidxJunit = "1.2.1"
androidxTestRules = "1.6.1"
androidxTestRunner = "1.6.2"
appcompat = "1.7.0"
constraintlayout = "2.1.4"
coreKtx = "1.13.1"
dokka = "1.9.20"
espressoCore = "3.6.1"
guava = "32.1.3-jre"
junit = "4.13.2"
kotlin = "2.0.20"
multidex = "2.0.1"
navigationFragmentKtx = "2.8.1"
preferenceKtx = "1.2.1"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
androidx-multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationFragmentKtx" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
androidx-rules = { module = "androidx.test:rules", version.ref = "androidxTestRules" }
androidx-runner = { module = "androidx.test:runner", version.ref = "androidxTestRunner" }
android-gradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
junit = { module = "junit:junit", version.ref = "junit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }

